apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: dso202-assignment-02
  labels:
    tier: database
spec:
  serviceName: db-svc        
  replicas: 1
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      tier: database
  template:
    metadata:
      labels:
        tier: database
    spec:
      containers:
        - name: db
          image: sarojsanyasi/dso202-db:1.0
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - configMapRef:
                name: dso202-config
            - secretRef:
                name: dso202-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
  updateStrategy:
    type: RollingUpdate
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain